services:
  database:
    image: mysql
    restart: always
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - backend-network

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-network

volumes:
  db:

networks:
  frontend-network:
  backend-network: